export type LoginEvent =
  | "LOGIN_SUCCESS"
  | "LOGIN_FAILURE"
  | "LOGOUT"
  | "TOKEN_EXPIRED"
  | "TOKEN_REVOKED"
  | "KICKED_OUT_BY_NEW_LOGIN"
  | "KICKED_OUT_BY_ADMIN"
  | "PASSWORD_RESET_REVOKED"
  | "USER_DISABLED_REVOKED";
