-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseColumn
create table db_column
(
    id               bigint auto_increment not null,
    database_id      bigint       not null,
    data_source_id   bigint       not null,
    table_id         bigint       not null,
    column_name      varchar(256) not null,
    alias            varchar(128),
    type_name        varchar(128),
    jdbc_type        int,
    column_size      int,
    decimal_digits   int,
    nullable_flag    bit,
    ordinal_position int,
    default_value    varchar(1000),
    remark_db        varchar(1000),
    remark_custom    varchar(1000),
    primary key (id),
    constraint uk_db_column unique (table_id, column_name)
);
create index idx_db_column_db on db_column (database_id);
create index idx_db_column_table on db_column (table_id);
create index idx_db_column_name on db_column (column_name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseSchema
create table db_schema
(
    id              bigint auto_increment not null,
    data_source_id  bigint,
    database_name   varchar(128) not null,
    alias           varchar(128),
    remark_custom   varchar(512),
    product_name    varchar(256),
    product_version longtext,
    driver_name     varchar(256),
    driver_version  varchar(256),
    fetched_at      datetime,
    created_at      datetime,
    primary key (id),
    constraint uk_db_schema_name unique (data_source_id, database_name)
);
create index idx_db_schema_source on db_schema (data_source_id);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseSource
create table db_source
(
    id             bigint auto_increment not null,
    name           varchar(128) not null,
    db_type        varchar(32)  not null,
    auth_mode      varchar(32)  not null,
    connect_mode   varchar(32),
    host           varchar(128),
    port           int,
    database_name  varchar(128),
    service_name   varchar(128),
    sid            varchar(128),
    driver_class   varchar(256),
    jdbc_url       varchar(512) not null,
    username       varchar(128) not null,
    password_enc   varchar(512),
    source_type    varchar(16)  not null,
    app_ds_key     varchar(128),
    remark_custom  varchar(512),
    extra_params   varchar(2000),
    ds_status      varchar(16)  not null,
    last_test_time datetime,
    last_ok_time   datetime,
    last_error     varchar(1000),
    primary key (id),
    constraint uk_db_source_name unique (name)
);
create index idx_db_source_name on db_source (name);
create index idx_db_source_type on db_source (db_type);
create index idx_db_source_status on db_source (ds_status);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseTable
create table db_table
(
    id             bigint auto_increment not null,
    database_id    bigint       not null,
    data_source_id bigint       not null,
    alias          varchar(128),
    table_catalog  varchar(128),
    table_schema   varchar(128),
    table_name     varchar(256) not null,
    table_type     varchar(32),
    remark_db      varchar(1000),
    remark_custom  varchar(1000),
    primary key (id),
    constraint uk_db_table unique (database_id, table_catalog, table_schema, table_name)
);
create index idx_db_table_db on db_table (database_id);
create index idx_db_table_name on db_table (table_name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.jsonfmt.domain.model.JsonFmtRecord
create table jsonfmt_record
(
    id              varchar(36)  not null,
    user_id         bigint       not null,
    name            varchar(128) not null,
    content         longtext,
    content_file_id varchar(36),
    order_no        int          not null,
    created_at      datetime     not null,
    updated_at      datetime     not null,
    primary key (id)
);
create index idx_jsonfmt_record_user_order on jsonfmt_record (user_id, order_no);
create index idx_jsonfmt_record_user_updated_at on jsonfmt_record (user_id, updated_at);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.ReminderOutbox
create table reminder_outbox
(
    id            bigint auto_increment not null,
    dedupe_key    varchar(200) not null,
    source_type   varchar(16)  not null,
    source_id     bigint       not null,
    user_id       bigint       not null,
    due_time      datetime     not null,
    title         varchar(300) not null,
    body          varchar(1000),
    outbox_status varchar(16)  not null,
    created_at    datetime     not null,
    sent_at       datetime,
    acked_at      datetime,
    delivery_id   bigint,
    primary key (id)
);
create index idx_reminder_due_time on reminder_outbox (due_time);
create index idx_reminder_status on reminder_outbox (outbox_status);
create index idx_reminder_delivery_id on reminder_outbox (delivery_id);
create unique index uk_reminder_dedupe on reminder_outbox (dedupe_key);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.ScheduleEvent
create table schedule_event
(
    id                   bigint auto_increment not null,
    title                varchar(300)  not null,
    start_time           datetime      not null,
    end_time             datetime,
    event_tz             varchar(64)   not null,
    freq                 varchar(16)   not null,
    freq_interval        int           not null,
    week_days_mask       int,
    day_of_month         int,
    month_of_year        int,
    until_time           datetime,
    count_limit          int,
    advance_seconds_json varchar(1000) not null,
    event_status         varchar(16)   not null,
    note                 varchar(1000),
    owner_id             bigint,
    primary key (id)
);
create index idx_schedule_start_time on schedule_event (start_time);
create index idx_schedule_status on schedule_event (event_status);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.TodoAttachment
create table todo_attachment
(
    id               bigint auto_increment not null,
    todo_id          bigint      not null,
    attachment_stage varchar(16) not null,
    file_id          varchar(64) not null,
    sort_no          bigint      not null,
    created_at       datetime    not null,
    primary key (id)
);
create index idx_todo_attachment_todo on todo_attachment (todo_id);
create index idx_todo_attachment_stage on todo_attachment (attachment_stage);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.TodoTask
create table todo_task
(
    id              bigint auto_increment not null,
    content         varchar(2000),
    due_time        datetime,
    remind_at       datetime,
    task_status     varchar(16) not null,
    sort_no         bigint      not null,
    owner_id        bigint,
    note            varchar(2000),
    completion_note varchar(2000),
    completed_at    datetime,
    created_at      datetime    not null,
    updated_at      datetime    not null,
    primary key (id)
);
create index idx_todo_due_time on todo_task (due_time);
create index idx_todo_status on todo_task (task_status);
create index idx_todo_sort_no on todo_task (sort_no);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.schemaforge.domain.model.DatabaseDdl
create table sf_database_ddl
(
    id                  varchar(36)  not null,
    managed_database_id bigint       not null,
    source_snapshot_id  varchar(36),
    target_snapshot_id  varchar(36)  not null,
    name                varchar(128) not null,
    remark              varchar(512),
    db_type             varchar(64),
    db_version          varchar(128),
    schema_name         varchar(128),
    logical_file_id     varchar(36)  not null,
    content_hash        varchar(128) not null,
    created_at          datetime     not null,
    primary key (id)
);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.schemaforge.domain.model.DatabaseSnapshot
create table sf_database_snapshot
(
    id                  varchar(36)  not null,
    managed_database_id bigint       not null,
    name                varchar(128) not null,
    remark              varchar(512),
    db_type             varchar(64),
    db_version          varchar(128),
    schema_name         varchar(128),
    logical_file_id     varchar(36)  not null,
    sql_logical_file_id varchar(36),
    content_hash        varchar(128) not null,
    created_at          datetime     not null,
    primary key (id)
);
