-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.ItemLedger
create table clinic_item_ledger
(
    id           bigint generated by default as identity not null,
    sku_id       bigint                                  not null,
    biz_type     varchar(16)                             not null,
    biz_id       bigint                                  not null,
    biz_line_id  bigint                                  not null,
    occurred_at  date                                    not null,
    qty          decimal(19, 4)                          not null,
    unit         varchar(32)                             not null,
    amount_total decimal(19, 2)                          not null,
    supplier_id  bigint,
    remark       varchar(512),
    primary key (id)
);
create index idx_clinic_ledger_sku on clinic_item_ledger (sku_id);
create index idx_clinic_ledger_type on clinic_item_ledger (biz_type);
create index idx_clinic_ledger_occurred on clinic_item_ledger (occurred_at);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.ItemSku
create table clinic_item_sku
(
    id           bigint generated by default as identity not null,
    spu_id       bigint                                  not null,
    display_name varchar(255)                            not null,
    manufacturer varchar(128),
    spec         varchar(128),
    enabled      boolean                                 not null,
    primary key (id)
);
create index idx_clinic_item_sku_spu on clinic_item_sku (spu_id);
create index idx_clinic_item_sku_name on clinic_item_sku (display_name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.ItemSpu
create table clinic_item_spu
(
    id       bigint generated by default as identity not null,
    category varchar(16)                             not null,
    name     varchar(128)                            not null,
    remark   varchar(512),
    primary key (id)
);
create index idx_clinic_item_spu_category on clinic_item_spu (category);
create index idx_clinic_item_spu_name on clinic_item_spu (name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.Purchase
create table clinic_purchase
(
    id           bigint generated by default as identity not null,
    supplier_id  bigint                                  not null,
    purchased_at date                                    not null,
    total_amount decimal(19, 2),
    remark       varchar(512),
    primary key (id)
);
create index idx_clinic_purchase_supplier on clinic_purchase (supplier_id);
create index idx_clinic_purchase_date on clinic_purchase (purchased_at);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.PurchaseLine
create table clinic_purchase_line
(
    id                bigint generated by default as identity not null,
    purchase_id       bigint                                  not null,
    sku_id            bigint                                  not null,
    qty               decimal(19, 4)                          not null,
    unit              varchar(32)                             not null,
    line_total_amount decimal(19, 2)                          not null,
    unit_price        decimal(19, 4)                          not null,
    remark            varchar(512),
    primary key (id)
);
create index idx_clinic_purchase_line_purchase on clinic_purchase_line (purchase_id);
create index idx_clinic_purchase_line_sku on clinic_purchase_line (sku_id);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.Sale
create table clinic_sale
(
    id            bigint generated by default as identity not null,
    sold_at       date                                    not null,
    total_amount  decimal(19, 2)                          not null,
    customer_name varchar(128),
    remark        varchar(512),
    primary key (id)
);
create index idx_clinic_sale_date on clinic_sale (sold_at);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.SaleLine
create table clinic_sale_line
(
    id                bigint generated by default as identity not null,
    sale_id           bigint                                  not null,
    sku_id            bigint                                  not null,
    qty               decimal(19, 4)                          not null,
    unit              varchar(32)                             not null,
    line_total_amount decimal(19, 2)                          not null,
    unit_price        decimal(19, 4)                          not null,
    remark            varchar(512),
    primary key (id)
);
create index idx_clinic_sale_line_sale on clinic_sale_line (sale_id);
create index idx_clinic_sale_line_sku on clinic_sale_line (sku_id);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.clinic.domain.model.Supplier
create table clinic_supplier
(
    id        bigint generated by default as identity not null,
    name      varchar(128)                            not null,
    name_norm varchar(128)                            not null,
    enabled   boolean                                 not null,
    remark    varchar(512),
    primary key (id),
    constraint uk_clinic_supplier_name_norm unique (name_norm)
);
create index idx_clinic_supplier_name on clinic_supplier (name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseColumn
create table db_column
(
    id               bigint generated by default as identity not null,
    database_id      bigint                                  not null,
    data_source_id   bigint                                  not null,
    table_id         bigint                                  not null,
    column_name      varchar(256)                            not null,
    alias            varchar(128),
    type_name        varchar(128),
    jdbc_type        integer,
    column_size      integer,
    decimal_digits   integer,
    nullable_flag    boolean,
    ordinal_position integer,
    default_value    varchar(1000),
    remark_db        varchar(1000),
    remark_custom    varchar(1000),
    primary key (id),
    constraint uk_db_column unique (table_id, column_name)
);
create index idx_db_column_db on db_column (database_id);
create index idx_db_column_table on db_column (table_id);
create index idx_db_column_name on db_column (column_name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseSchema
create table db_schema
(
    id              bigint generated by default as identity not null,
    data_source_id  bigint,
    database_name   varchar(128)                            not null,
    alias           varchar(128),
    remark_custom   varchar(512),
    product_name    varchar(256),
    product_version text,
    driver_name     varchar(256),
    driver_version  varchar(256),
    fetched_at      timestamp(6),
    created_at      timestamp(6),
    primary key (id),
    constraint uk_db_schema_name unique (data_source_id, database_name)
);
create index idx_db_schema_source on db_schema (data_source_id);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseSource
create table db_source
(
    id             bigint generated by default as identity not null,
    name           varchar(128)                            not null,
    db_type        varchar(32)                             not null,
    auth_mode      varchar(32)                             not null,
    connect_mode   varchar(32),
    host           varchar(128),
    port           integer,
    database_name  varchar(128),
    service_name   varchar(128),
    sid            varchar(128),
    driver_class   varchar(256),
    jdbc_url       varchar(512)                            not null,
    username       varchar(128)                            not null,
    password_enc   varchar(512),
    source_type    varchar(16)                             not null,
    app_ds_key     varchar(128),
    remark_custom  varchar(512),
    extra_params   varchar(2000),
    ds_status      varchar(16)                             not null,
    last_test_time timestamp(6),
    last_ok_time   timestamp(6),
    last_error     varchar(1000),
    primary key (id),
    constraint uk_db_source_name unique (name)
);
create index idx_db_source_name on db_source (name);
create index idx_db_source_type on db_source (db_type);
create index idx_db_source_status on db_source (ds_status);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.datasource.domain.model.DatabaseTable
create table db_table
(
    id             bigint generated by default as identity not null,
    database_id    bigint                                  not null,
    data_source_id bigint                                  not null,
    alias          varchar(128),
    table_catalog  varchar(128),
    table_schema   varchar(128),
    table_name     varchar(256)                            not null,
    table_type     varchar(32),
    remark_db      varchar(1000),
    remark_custom  varchar(1000),
    primary key (id),
    constraint uk_db_table unique (database_id, table_catalog, table_schema, table_name)
);
create index idx_db_table_db on db_table (database_id);
create index idx_db_table_name on db_table (table_name);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.jsonfmt.domain.model.JsonFmtRecord
create table jsonfmt_record
(
    id              varchar(36)  not null,
    user_id         bigint       not null,
    name            varchar(128) not null,
    content         text,
    content_file_id varchar(36),
    order_no        integer      not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    primary key (id)
);
create index idx_jsonfmt_record_user_order on jsonfmt_record (user_id, order_no);
create index idx_jsonfmt_record_user_updated_at on jsonfmt_record (user_id, updated_at);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.ReminderOutbox
create table reminder_outbox
(
    id            bigint generated by default as identity not null,
    dedupe_key    varchar(200)                            not null,
    source_type   varchar(16)                             not null,
    source_id     bigint                                  not null,
    user_id       bigint                                  not null,
    due_time      timestamp(6)                            not null,
    title         varchar(300)                            not null,
    body          varchar(1000),
    outbox_status varchar(16)                             not null,
    created_at    timestamp(6)                            not null,
    sent_at       timestamp(6),
    acked_at      timestamp(6),
    delivery_id   bigint,
    primary key (id)
);
create index idx_reminder_due_time on reminder_outbox (due_time);
create index idx_reminder_status on reminder_outbox (outbox_status);
create index idx_reminder_delivery_id on reminder_outbox (delivery_id);
create unique index uk_reminder_dedupe on reminder_outbox (dedupe_key);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.ScheduleEvent
create table schedule_event
(
    id                   bigint generated by default as identity not null,
    title                varchar(300)                            not null,
    start_time           timestamp(6)                            not null,
    end_time             timestamp(6),
    event_tz             varchar(64)                             not null,
    freq                 varchar(16)                             not null,
    freq_interval        integer                                 not null,
    week_days_mask       integer,
    day_of_month         integer,
    month_of_year        integer,
    until_time           timestamp(6),
    count_limit          integer,
    advance_seconds_json varchar(1000)                           not null,
    event_status         varchar(16)                             not null,
    note                 varchar(1000),
    owner_id             bigint,
    primary key (id)
);
create index idx_schedule_start_time on schedule_event (start_time);
create index idx_schedule_status on schedule_event (event_status);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.TodoAttachment
create table todo_attachment
(
    id               bigint generated by default as identity not null,
    todo_id          bigint                                  not null,
    attachment_stage varchar(16)                             not null,
    file_id          varchar(64)                             not null,
    sort_no          bigint                                  not null,
    created_at       timestamp(6)                            not null,
    primary key (id)
);
create index idx_todo_attachment_todo on todo_attachment (todo_id);
create index idx_todo_attachment_stage on todo_attachment (attachment_stage);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.reminder.domain.model.TodoTask
create table todo_task
(
    id              bigint generated by default as identity not null,
    content         varchar(2000),
    due_time        timestamp(6),
    remind_at       timestamp(6),
    task_status     varchar(16)                             not null,
    sort_no         bigint                                  not null,
    owner_id        bigint,
    note            varchar(2000),
    completion_note varchar(2000),
    completed_at    timestamp(6),
    created_at      timestamp(6)                            not null,
    updated_at      timestamp(6)                            not null,
    primary key (id)
);
create index idx_todo_due_time on todo_task (due_time);
create index idx_todo_status on todo_task (task_status);
create index idx_todo_sort_no on todo_task (sort_no);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.schemaforge.domain.model.DatabaseDdl
create table sf_database_ddl
(
    id                  varchar(36)  not null,
    managed_database_id bigint       not null,
    source_snapshot_id  varchar(36),
    target_snapshot_id  varchar(36)  not null,
    name                varchar(128) not null,
    remark              varchar(512),
    db_type             varchar(64),
    db_version          varchar(128),
    schema_name         varchar(128),
    logical_file_id     varchar(36)  not null,
    content_hash        varchar(128) not null,
    created_at          timestamp(6) not null,
    primary key (id)
);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.schemaforge.domain.model.DatabaseSnapshot
create table sf_database_snapshot
(
    id                  varchar(36)  not null,
    managed_database_id bigint       not null,
    name                varchar(128) not null,
    remark              varchar(512),
    db_type             varchar(64),
    db_version          varchar(128),
    schema_name         varchar(128),
    logical_file_id     varchar(36)  not null,
    sql_logical_file_id varchar(36),
    content_hash        varchar(128) not null,
    created_at          timestamp(6) not null,
    primary key (id)
);
