-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.scheduler.domain.model.SchedulerJobDefinition
create table sched_job
(
    job_id             varchar(128) not null,
    namespace          varchar(64)  not null,
    name               varchar(128) not null,
    job_source         varchar(32)  not null,
    job_type           varchar(32)  not null,
    handler_key        varchar(128),
    schedule_rule_type varchar(128) not null,
    schedule_rule_body bytea,
    payload_type       varchar(256),
    payload_body       bytea,
    enabled            boolean      not null,
    deleted            boolean      not null,
    allow_concurrent   boolean      not null,
    version_no         integer      not null,
    remark             varchar(512),
    created_at         timestamp(6) not null,
    updated_at         timestamp(6) not null,
    primary key (job_id)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.scheduler.domain.model.SchedulerJobExecution
create table sched_job_execution
(
    execution_id     varchar(64)  not null,
    job_id           varchar(128) not null,
    scheduled_time   timestamp(6),
    start_time       timestamp(6) not null,
    end_time         timestamp(6),
    execution_result varchar(32),
    duration_ms      bigint,
    trigger_type     varchar(32)  not null,
    result_code      varchar(64),
    result_message   varchar(2000),
    error_message    varchar(2000),
    error_stack      text,
    created_at       timestamp(6) not null,
    primary key (execution_id)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.scheduler.domain.model.SchedulerJobRuntime
create table sched_job_runtime
(
    job_id               varchar(128) not null,
    job_status           varchar(32)  not null,
    next_fire_time       timestamp(6),
    last_fire_time       timestamp(6),
    last_success_time    timestamp(6),
    last_failure_time    timestamp(6),
    consecutive_failures bigint       not null,
    last_error_message   varchar(2000),
    last_duration_ms     bigint,
    current_execution_id varchar(64),
    updated_at           timestamp(6) not null,
    primary key (job_id)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.resource.domain.model.Api
create table sys_api
(
    id                  bigint generated by default as identity not null,
    module              varchar(128)                            not null,
    protocol            varchar(16)                             not null,
    http_method         varchar(16)                             not null,
    path_pattern        varchar(512)                            not null,
    handler_class       varchar(512),
    handler_method      varchar(128),
    permission_declared boolean                                 not null,
    access_type         varchar(32)                             not null,
    user_type           varchar(16),
    audit_declared      boolean                                 not null,
    audit_resource      varchar(128),
    audit_action        varchar(128),
    audit_description   varchar(512),
    sort_options_json   text,
    enabled             boolean                                 not null,
    system_builtin      boolean                                 not null,
    created_at          timestamp(6)                            not null,
    updated_at          timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_api_unique on sys_api (module, protocol, http_method, path_pattern);
create index idx_sys_api_module on sys_api (module);
create index idx_sys_api_path on sys_api (module, http_method, path_pattern);
create index idx_sys_api_access_type on sys_api (access_type);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.resource.domain.model.ApiPermission
create table sys_api_permission
(
    id             bigint generated by default as identity not null,
    api_id         bigint                                  not null,
    permission_id  bigint                                  not null,
    system_builtin boolean                                 not null,
    created_at     timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_api_permission_unique on sys_api_permission (api_id, permission_id);
create index idx_sys_api_permission_api_id on sys_api_permission (api_id);
create index idx_sys_api_permission_permission_id on sys_api_permission (permission_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.audit.domain.model.AuditLog
create table sys_audit_log
(
    id                    bigint generated by default as identity not null,
    trace_id              varchar(128),
    request_id            varchar(128),
    operator_user_id      bigint,
    operator_username     varchar(128),
    operator_user_type    varchar(32),
    application_code      varchar(128),
    protocol              varchar(16),
    http_method           varchar(16),
    path_pattern          varchar(512),
    request_uri           varchar(1024),
    permission_codes      text,
    audit_resource        varchar(128),
    audit_action          varchar(128),
    audit_description     varchar(512),
    audit_level           varchar(16),
    request_ip            varchar(128),
    user_agent            varchar(1024),
    request_param_summary text,
    request_body_summary  text,
    response_summary      text,
    success               boolean,
    error_code            varchar(128),
    error_message         text,
    started_at            timestamp(6),
    ended_at              timestamp(6),
    duration_ms           bigint,
    created_at            timestamp(6)                            not null,
    primary key (id)
);
create index idx_sys_audit_log_trace_id on sys_audit_log (trace_id);
create index idx_sys_audit_log_request_id on sys_audit_log (request_id);
create index idx_sys_audit_log_operator_user_id on sys_audit_log (operator_user_id);
create index idx_sys_audit_log_application_code on sys_audit_log (application_code);
create index idx_sys_audit_log_path on sys_audit_log (application_code, http_method, path_pattern);
create index idx_sys_audit_log_resource_action on sys_audit_log (audit_resource, audit_action);
create index idx_sys_audit_log_success on sys_audit_log (success);
create index idx_sys_audit_log_created_at on sys_audit_log (created_at);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.dict.domain.model.DictItem
create table sys_dict_item
(
    id             varchar(64)  not null,
    dict_type_id   varchar(64)  not null,
    parent_item_id varchar(64),
    item_code      varchar(128) not null,
    item_label     varchar(128) not null,
    item_value     varchar(512) not null,
    sort_no        integer      not null,
    enabled        boolean      not null,
    is_default     boolean      not null,
    tag_color      varchar(32),
    tag_type       varchar(32),
    extra_json     varchar(4000),
    description    varchar(255),
    created_at     timestamp(6) not null,
    created_by     varchar(64)  not null,
    updated_at     timestamp(6) not null,
    updated_by     varchar(64)  not null,
    primary key (id),
    constraint uk_sys_dict_item_code unique (dict_type_id, item_code)
);
create index idx_sys_dict_item_type on sys_dict_item (dict_type_id);
create index idx_sys_dict_item_parent on sys_dict_item (parent_item_id);
create index idx_sys_dict_item_enabled on sys_dict_item (enabled);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.dict.domain.model.DictType
create table sys_dict_type
(
    id             varchar(64)  not null,
    code           varchar(128) not null,
    name           varchar(128) not null,
    description    varchar(255),
    enum_class     varchar(255),
    value_type     varchar(32)  not null,
    structure_type varchar(32)  not null,
    source_type    varchar(32)  not null,
    enabled        boolean      not null,
    created_at     timestamp(6) not null,
    created_by     varchar(64)  not null,
    updated_at     timestamp(6) not null,
    updated_by     varchar(64)  not null,
    primary key (id),
    constraint uk_sys_dict_type_code unique (code)
);
create index idx_sys_dict_type_enabled on sys_dict_type (enabled);
create index idx_sys_dict_type_source on sys_dict_type (source_type);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.resource.domain.model.Resource
create table sys_resource
(
    id             bigint generated by default as identity not null,
    code           varchar(128)                            not null,
    parent_id      bigint,
    name           varchar(128)                            not null,
    resource_type  varchar(32)                             not null,
    path           varchar(512),
    component      varchar(512),
    icon           varchar(128),
    sort_no        integer                                 not null,
    visible        boolean                                 not null,
    enabled        boolean                                 not null,
    default_entry  boolean                                 not null,
    system_builtin boolean                                 not null,
    remark         varchar(512),
    created_at     timestamp(6)                            not null,
    updated_at     timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_resource_code on sys_resource (code);
create index idx_sys_resource_parent_id on sys_resource (parent_id);
create index idx_sys_resource_type on sys_resource (resource_type);
create index idx_sys_resource_sort_no on sys_resource (sort_no);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.resource.domain.model.ResourcePermission
create table sys_resource_permission
(
    id             bigint generated by default as identity not null,
    resource_id    bigint                                  not null,
    permission_id  bigint                                  not null,
    system_builtin boolean                                 not null,
    created_at     timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_resource_permission_unique on sys_resource_permission (resource_id, permission_id);
create index idx_sys_resource_permission_resource_id on sys_resource_permission (resource_id);
create index idx_sys_resource_permission_permission_id on sys_resource_permission (permission_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.auth.domain.model.LoginEvent
create table sys_login_event
(
    id             bigint generated by default as identity not null,
    user_id        bigint,
    username       varchar(64),
    event_type     varchar(32)                             not null,
    success        boolean                                 not null,
    failure_reason varchar(128),
    session_id     bigint,
    login_ip       varchar(128),
    operator_id    bigint,
    occurred_at    timestamp(6)                            not null,
    remark         varchar(255),
    primary key (id)
);
create index idx_sys_login_log_user on sys_login_event (user_id);
create index idx_sys_login_log_event_type on sys_login_event (event_type);
create index idx_sys_login_log_occurred_at on sys_login_event (occurred_at);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.auth.domain.model.LoginSession
create table sys_login_session
(
    id                       bigint generated by default as identity not null,
    user_id                  bigint                                  not null,
    token_id                 varchar(64)                             not null,
    token_hash               varchar(128)                            not null,
    session_status           varchar(16)                             not null,
    permission_snapshot_json text                                    not null,
    menu_snapshot_json       text                                    not null,
    function_snapshot_json   text                                    not null,
    login_ip                 varchar(128),
    user_agent               varchar(512),
    login_at                 timestamp(6)                            not null,
    expires_at               timestamp(6)                            not null,
    last_access_at           timestamp(6)                            not null,
    logout_at                timestamp(6),
    revoked_at               timestamp(6),
    revoked_by               varchar(64),
    revoked_reason           varchar(512),
    created_at               timestamp(6)                            not null,
    updated_at               timestamp(6)                            not null,
    created_by               varchar(64),
    updated_by               varchar(64),
    primary key (id)
);
create unique index idx_sys_login_session_token_hash on sys_login_session (token_hash);
create index idx_sys_login_session_user_status on sys_login_session (user_id, session_status);




-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.notify.domain.model.MessageDelivery
create table sys_message_delivery
(
    id                      bigint generated by default as identity not null,
    user_id                 bigint                                  not null,
    user_type               varchar(16),
    notification_id         bigint,
    msg_type                varchar(64)                             not null,
    title                   varchar(300)                            not null,
    content                 varchar(2000),
    route                   varchar(500),
    priority                varchar(20)                             not null,
    panel_auto_open         boolean                                 not null,
    os_notification_enabled boolean                                 not null,
    biz_type                varchar(64),
    biz_id                  varchar(128),
    delivery_status         varchar(16)                             not null,
    created_at              timestamp(6)                            not null,
    sent_at                 timestamp(6),
    acked_at                timestamp(6),
    primary key (id)
);
create index idx_msg_delivery_user_status on sys_message_delivery (user_type, user_id, delivery_status);
create index idx_msg_delivery_user_id on sys_message_delivery (user_type, user_id, id);
create index idx_msg_delivery_user_notification on sys_message_delivery (user_type, user_id, notification_id);
-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.notify.domain.model.Notification
create table sys_notification
(
    id         bigint generated by default as identity not null,
    user_id    bigint                                  not null,
    user_type  varchar(16),
    title      varchar(255)                            not null,
    content    varchar(255),
    msg_type   varchar(20)                             not null,
    priority   varchar(20)                             not null,
    route      varchar(500),
    is_read    boolean                                 not null,
    created_at timestamp(6)                            not null,
    read_at    timestamp(6),
    primary key (id)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.resource.domain.model.Permission
create table sys_permission
(
    id             bigint generated by default as identity not null,
    code           varchar(128)                            not null,
    name           varchar(128)                            not null,
    user_scope     varchar(16)                             not null,
    created_at     timestamp(6)                            not null,
    updated_at     timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_permission_code on sys_permission (code);
create index idx_sys_permission_user_scope on sys_permission (user_scope);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.auth.domain.model.RefreshToken
create table sys_refresh_token
(
    id                 bigint generated by default as identity not null,
    user_id            bigint                                  not null,
    refresh_token_id   varchar(64)                             not null,
    refresh_token_hash varchar(128)                            not null,
    status             varchar(16)                             not null,
    issued_at          timestamp(6)                            not null,
    expires_at         timestamp(6)                            not null,
    revoked_at         timestamp(6),
    revoked_reason     varchar(512),
    client_info        varchar(1024),
    created_at         timestamp(6)                            not null,
    updated_at         timestamp(6)                            not null,
    primary key (id)
);
create index idx_sys_refresh_token_user_id on sys_refresh_token (user_id);
create index idx_sys_refresh_token_user_status on sys_refresh_token (user_id, status);
create unique index idx_sys_refresh_token_token_id on sys_refresh_token (refresh_token_id);
create unique index idx_sys_refresh_token_hash on sys_refresh_token (refresh_token_hash);
create index idx_sys_refresh_token_expires_at on sys_refresh_token (expires_at);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.role.domain.model.Role
create table sys_role
(
    id             bigint generated by default as identity not null,
    code           varchar(128)                            not null,
    name           varchar(128)                            not null,
    description    varchar(512),
    enabled        boolean                                 not null,
    system_builtin boolean                                 not null,
    created_by     bigint,
    created_at     timestamp(6)                            not null,
    updated_by     bigint,
    updated_at     timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_role_code on sys_role (code);
create index idx_sys_role_enabled on sys_role (enabled);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.role.domain.model.RoleResource
create table sys_role_resource
(
    id          bigint generated by default as identity not null,
    role_id     bigint                                  not null,
    resource_id bigint                                  not null,
    created_by  bigint,
    created_at  timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_role_resource_unique on sys_role_resource (role_id, resource_id);
create index idx_sys_role_resource_role_id on sys_role_resource (role_id);
create index idx_sys_role_resource_resource_id on sys_role_resource (resource_id);

-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.file.domain.model.LogicalFile
create table sys_storage_file
(
    id               varchar(36)  not null,
    owner_type       varchar(32)  not null,
    owner_id         varchar(64)  not null,
    parent_id        varchar(36),
    node_type        varchar(16)  not null,
    file_name        varchar(256) not null,
    physical_file_id varchar(36),
    purpose          varchar(64),
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    primary key (id),
    constraint uk_sys_storage_file_node unique (owner_type, owner_id, parent_id, node_type, file_name)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.file.domain.model.PhysicalFile
create table sys_storage_physical_file
(
    id            varchar(36)  not null,
    hash          varchar(128) not null,
    relative_path varchar(256) not null,
    file_name     varchar(128) not null,
    file_size     bigint       not null,
    content_type  varchar(128),
    ref_count     integer      not null,
    created_at    timestamp(6) not null,
    primary key (id)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.task.domain.model.TaskConfig
create table sys_task_config
(
    code               varchar(64) not null,
    cron_expr          varchar(64),
    task_status        varchar(32) not null,
    last_run_at        timestamp(6),
    last_run_status    varchar(32),
    last_error_message varchar(2000),
    primary key (code)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.task.domain.model.TaskDefinition
create table sys_task_definition
(
    code        varchar(64)  not null,
    name        varchar(128) not null,
    description varchar(512),
    bean_name   varchar(128) not null,
    method_name varchar(128) not null,
    is_removed  boolean      not null,
    updated_at  timestamp(6),
    primary key (code)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.webuser.domain.model.WebUser
create table tb_user
(
    id                  bigint generated by default as identity not null,
    display_name        varchar(128),
    nickname            varchar(128),
    status              varchar(16)                             not null,
    register_method     varchar(32)                             not null,
    register_channel    varchar(32)                             not null,
    register_source     varchar(128),
    register_ip         varchar(128),
    register_user_agent varchar(255),
    primary_identity_id bigint,
    token_version       bigint                                  not null,
    token_not_before    timestamp(6),
    last_login_at       timestamp(6),
    last_login_ip       varchar(128),
    disabled_at         timestamp(6),
    disabled_by         varchar(64),
    disabled_reason     varchar(255),
    cancelled_at        timestamp(6),
    cancel_reason       varchar(255),
    created_at          timestamp(6)                            not null,
    created_by          varchar(64),
    updated_at          timestamp(6)                            not null,
    updated_by          varchar(64),
    primary key (id)
);
create index idx_tb_user_status on tb_user (status);
create index idx_tb_user_primary_identity on tb_user (primary_identity_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.webuser.domain.model.WebUserIdentity
create table tb_identity
(
    id               bigint generated by default as identity not null,
    user_id          bigint                                  not null,
    identity_type    varchar(16)                             not null,
    identity_value   varchar(128)                            not null,
    normalized_value varchar(128),
    identity_hash    varchar(128),
    provider_code    varchar(64),
    provider_subject varchar(128),
    verified         boolean                                 not null,
    login_enabled    boolean                                 not null,
    bind_status      varchar(16)                             not null,
    created_at       timestamp(6)                            not null,
    created_by       varchar(64),
    updated_at       timestamp(6)                            not null,
    updated_by       varchar(64),
    primary key (id)
);
create index idx_tb_identity_user on tb_identity (user_id);
create index idx_tb_identity_hash on tb_identity (identity_type, identity_hash);
create index idx_tb_identity_provider on tb_identity (provider_code, provider_subject);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.webuser.domain.model.WebUserCredential
create table tb_credential
(
    id              bigint generated by default as identity not null,
    user_id         bigint                                  not null,
    identity_id     bigint,
    credential_type varchar(16)                             not null,
    secret_hash     varchar(128)                            not null,
    secret_algo     varchar(32)                             not null,
    status          varchar(16)                             not null,
    expires_at      timestamp(6),
    created_at      timestamp(6)                            not null,
    created_by      varchar(64),
    updated_at      timestamp(6)                            not null,
    updated_by      varchar(64),
    primary key (id)
);
create index idx_tb_credential_user on tb_credential (user_id);
create index idx_tb_credential_identity on tb_credential (identity_id);
create index idx_tb_credential_type on tb_credential (credential_type, status);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.webuser.domain.model.WebUserCurrentIdentity
create table tb_current_identity
(
    id               bigint generated by default as identity not null,
    identity_type    varchar(16)                             not null,
    identity_hash    varchar(128),
    provider_code    varchar(64),
    provider_subject varchar(128),
    user_id          bigint                                  not null,
    identity_id      bigint                                  not null,
    created_at       timestamp(6)                            not null,
    updated_at       timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_tb_current_identity_hash on tb_current_identity (identity_type, identity_hash);
create unique index idx_tb_current_identity_provider on tb_current_identity (provider_code, provider_subject);
create index idx_tb_current_identity_user on tb_current_identity (user_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.webuser.domain.model.WebUserRestriction
create table tb_user_restriction
(
    id                bigint generated by default as identity not null,
    user_id           bigint                                  not null,
    restriction_type  varchar(32)                             not null,
    restriction_scope varchar(16)                             not null,
    reason            varchar(255),
    start_at          timestamp(6)                            not null,
    end_at            timestamp(6),
    created_at        timestamp(6)                            not null,
    created_by        varchar(64),
    updated_at        timestamp(6)                            not null,
    updated_by        varchar(64),
    primary key (id)
);
create index idx_tb_user_restriction_user on tb_user_restriction (user_id);
create index idx_tb_user_restriction_scope on tb_user_restriction (restriction_scope, start_at, end_at);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.webuser.domain.model.WebUserLifecycleEvent
create table tb_user_lifecycle_event
(
    id            bigint generated by default as identity not null,
    user_id       bigint                                  not null,
    event_type    varchar(32)                             not null,
    operator_type varchar(16),
    operator_id   varchar(64),
    metadata_json oid,
    created_at    timestamp(6)                            not null,
    primary key (id)
);
create index idx_tb_user_event_user on tb_user_lifecycle_event (user_id);
create index idx_tb_user_event_type on tb_user_lifecycle_event (event_type, created_at);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.user.domain.model.User
create table sys_user
(
    id                       bigint generated by default as identity (start with 1001) not null,
    user_type                varchar(16)                                               not null,
    username                 varchar(32)                                               not null,
    nickname                 varchar(64)                                               not null,
    password_hash            varchar(128)                                              not null,
    password_algo            varchar(128)                                              not null,
    user_status              varchar(16)                                               not null,
    deleted_flag             boolean                                                   not null,
    last_password_changed_at timestamp(6),
    created_at               timestamp(6)                                              not null,
    created_by               varchar(64),
    updated_at               timestamp(6)                                              not null,
    updated_by               varchar(64),
    primary key (id)
);
create unique index idx_sys_user_username on sys_user (username);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.config.domain.model.Config
create table sys_config
(
    code              varchar(128)  not null,
    config_value      varchar(4000) not null,
    config_value_type varchar(32)   not null,
    description       varchar(256)  not null,
    level             varchar(16)   not null,
    expired           boolean       not null,
    primary key (code)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.user.domain.model.UserConfig
create table sys_user_config
(
    id           bigint generated by default as identity not null,
    user_id      bigint                                  not null,
    config_code  varchar(128)                            not null,
    config_value varchar(4000)                           not null,
    primary key (id),
    constraint uk_user_config unique (user_id, config_code)
);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.user.domain.model.UserPermission
create table sys_user_permission
(
    id            bigint generated by default as identity not null,
    user_id       bigint                                  not null,
    permission_id bigint                                  not null,
    created_at    timestamp(6)                            not null,
    created_by    bigint,
    primary key (id),
    constraint uk_sys_user_permission_user_permission unique (user_id, permission_id)
);
create index idx_sys_user_permission_user_id on sys_user_permission (user_id);
create index idx_sys_user_permission_permission_id on sys_user_permission (permission_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.notify.domain.model.UserPushSubscription
create table sys_user_push_subscription
(
    id           bigint generated by default as identity not null,
    user_id      bigint                                  not null,
    user_type    varchar(16),
    device_id    varchar(128)                            not null,
    endpoint     varchar(2000)                           not null,
    p256dh       varchar(512)                            not null,
    auth_secret  varchar(512)                            not null,
    active       boolean                                 not null,
    created_at   timestamp(6)                            not null,
    updated_at   timestamp(6)                            not null,
    last_push_at timestamp(6),
    last_error   varchar(1000),
    primary key (id),
    constraint uk_push_user_device unique (user_type, user_id, device_id)
);
create index idx_push_user_active on sys_user_push_subscription (user_type, user_id, active);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.user.domain.model.UserRole
create table sys_user_role
(
    id         bigint generated by default as identity not null,
    user_id    bigint                                  not null,
    role_id    bigint                                  not null,
    created_by bigint,
    created_at timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_role_unique on sys_user_role (user_id, role_id);
create index idx_sys_user_role_user_id on sys_user_role (user_id);
create index idx_sys_user_role_role_id on sys_user_role (role_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.ProductApplication
create table sys_product_application
(
    id                bigint generated by default as identity not null,
    application_code  varchar(128)                            not null,
    application_name  varchar(128)                            not null,
    description       varchar(512),
    icon              varchar(256),
    route_path        varchar(512),
    component_path    varchar(512),
    enabled           boolean                                 not null,
    system_built_in   boolean                                 not null,
    display_order     integer                                 not null,
    created_by        bigint,
    created_at        timestamp(6)                            not null,
    updated_by        bigint,
    updated_at        timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_product_application_code on sys_product_application (application_code);
create index idx_sys_product_application_enabled on sys_product_application (enabled);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.ProductFeature
create table sys_product_feature
(
    id              bigint generated by default as identity not null,
    application_id  bigint                                  not null,
    feature_code    varchar(128)                            not null,
    feature_name    varchar(128)                            not null,
    feature_type    varchar(32)                             not null,
    description     varchar(512),
    enabled         boolean                                 not null,
    system_built_in boolean                                 not null,
    display_order   integer                                 not null,
    created_by      bigint,
    created_at      timestamp(6)                            not null,
    updated_by      bigint,
    updated_at      timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_product_feature_unique on sys_product_feature (application_id, feature_code);
create index idx_sys_product_feature_application_id on sys_product_feature (application_id);
create index idx_sys_product_feature_type on sys_product_feature (feature_type);
create index idx_sys_product_feature_enabled on sys_product_feature (enabled);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.ProductFeaturePermissionBinding
create table sys_product_feature_permission_binding
(
    id              bigint generated by default as identity not null,
    application_id  bigint                                  not null,
    feature_id      bigint                                  not null,
    permission_id   bigint                                  not null,
    system_built_in boolean                                 not null,
    created_at      timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_product_feature_permission_binding_unique on sys_product_feature_permission_binding (feature_id, permission_id);
create index idx_sys_product_feature_permission_binding_application_id on sys_product_feature_permission_binding (application_id);
create index idx_sys_product_feature_permission_binding_feature_id on sys_product_feature_permission_binding (feature_id);
create index idx_sys_product_feature_permission_binding_permission_id on sys_product_feature_permission_binding (permission_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.UserApplicationPackage
create table sys_user_application_package
(
    id              bigint generated by default as identity not null,
    package_code    varchar(128)                            not null,
    package_name    varchar(128)                            not null,
    package_type    varchar(32)                             not null,
    description     varchar(512),
    enabled         boolean                                 not null,
    default_package boolean                                 not null,
    system_built_in boolean                                 not null,
    display_order   integer                                 not null,
    created_by      bigint,
    created_at      timestamp(6)                            not null,
    updated_by      bigint,
    updated_at      timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_application_package_code on sys_user_application_package (package_code);
create index idx_sys_user_application_package_type on sys_user_application_package (package_type);
create index idx_sys_user_application_package_enabled on sys_user_application_package (enabled);
create index idx_sys_user_application_package_default on sys_user_application_package (default_package);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.UserApplicationPackageMember
create table sys_user_application_package_member
(
    id         bigint generated by default as identity not null,
    package_id bigint                                  not null,
    user_id    bigint                                  not null,
    created_by bigint,
    created_at timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_application_package_member_unique on sys_user_application_package_member (package_id, user_id);
create index idx_sys_user_application_package_member_package_id on sys_user_application_package_member (package_id);
create index idx_sys_user_application_package_member_user_id on sys_user_application_package_member (user_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.UserPackageApplicationAccess
create table sys_user_package_application_access
(
    id                   bigint generated by default as identity not null,
    package_id           bigint                                  not null,
    application_id       bigint                                  not null,
    feature_access_scope varchar(16)                             not null,
    system_built_in      boolean                                 not null,
    created_by           bigint,
    created_at           timestamp(6)                            not null,
    updated_by           bigint,
    updated_at           timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_package_application_access_unique on sys_user_package_application_access (package_id, application_id);
create index idx_sys_user_package_application_access_package_id on sys_user_package_application_access (package_id);
create index idx_sys_user_package_application_access_application_id on sys_user_package_application_access (application_id);
create index idx_sys_user_package_application_access_scope on sys_user_package_application_access (feature_access_scope);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.UserPackageFeatureAccess
create table sys_user_package_feature_access
(
    id              bigint generated by default as identity not null,
    package_id      bigint                                  not null,
    application_id  bigint                                  not null,
    feature_id      bigint                                  not null,
    system_built_in boolean                                 not null,
    created_by      bigint,
    created_at      timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_package_feature_access_unique on sys_user_package_feature_access (package_id, feature_id);
create index idx_sys_user_package_feature_access_package_id on sys_user_package_feature_access (package_id);
create index idx_sys_user_package_feature_access_application_id on sys_user_package_feature_access (application_id);
create index idx_sys_user_package_feature_access_feature_id on sys_user_package_feature_access (feature_id);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.UserApplicationOverride
create table sys_user_application_override
(
    id                   bigint generated by default as identity not null,
    user_id              bigint                                  not null,
    application_id       bigint                                  not null,
    override_type        varchar(16)                             not null,
    feature_access_scope varchar(16)                             not null,
    reason               varchar(512),
    created_by           bigint,
    created_at           timestamp(6)                            not null,
    updated_by           bigint,
    updated_at           timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_application_override_unique on sys_user_application_override (user_id, application_id);
create index idx_sys_user_application_override_user_id on sys_user_application_override (user_id);
create index idx_sys_user_application_override_application_id on sys_user_application_override (application_id);
create index idx_sys_user_application_override_type on sys_user_application_override (override_type);
create index idx_sys_user_application_override_scope on sys_user_application_override (feature_access_scope);


-- generated by BootstrapSqlGenerator, do not edit by hand
-- entity: com.corwin.system.userfeature.domain.model.UserFeatureOverride
create table sys_user_feature_override
(
    id             bigint generated by default as identity not null,
    user_id        bigint                                  not null,
    application_id bigint                                  not null,
    feature_id     bigint                                  not null,
    override_type  varchar(16)                             not null,
    reason         varchar(512),
    created_by     bigint,
    created_at     timestamp(6)                            not null,
    updated_by     bigint,
    updated_at     timestamp(6)                            not null,
    primary key (id)
);
create unique index idx_sys_user_feature_override_unique on sys_user_feature_override (user_id, feature_id);
create index idx_sys_user_feature_override_user_id on sys_user_feature_override (user_id);
create index idx_sys_user_feature_override_application_id on sys_user_feature_override (application_id);
create index idx_sys_user_feature_override_feature_id on sys_user_feature_override (feature_id);
create index idx_sys_user_feature_override_type on sys_user_feature_override (override_type);
