<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.corwin</groupId>
        <artifactId>breezy</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>dependencies</artifactId>
    <packaging>pom</packaging>
    <name>dependencies</name>

    <properties>
        <p6spy-starter.version>1.12.1</p6spy-starter.version>
        <jbcrypt.version>0.4</jbcrypt.version>
        <jjwt.version>0.12.6</jjwt.version>
        <log4j-core.version>2.25.3</log4j-core.version>
        <liquibase.version>4.33.0</liquibase.version>
        <web-push.version>5.1.1</web-push.version>
        <bouncycastle.version>1.83</bouncycastle.version>
        <disruptor.version>4.0.0</disruptor.version>
        <caffeine.version>3.2.3</caffeine.version>
        <mybatis.version>3.5.19</mybatis.version>
        <mybatis-spring.version>3.0.5</mybatis-spring.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.corwin</groupId>
                <artifactId>framework</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.corwin</groupId>
                <artifactId>system</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.corwin</groupId>
                <artifactId>business</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.corwin</groupId>
                <artifactId>app</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${log4j-core.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>com.github.gavlyukovskiy</groupId>
                <artifactId>p6spy-spring-boot-starter</artifactId>
                <version>${p6spy-starter.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mindrot</groupId>
                <artifactId>jbcrypt</artifactId>
                <version>${jbcrypt.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
                <scope>runtime</scope>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
                <scope>runtime</scope>
            </dependency>

            <dependency>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-core</artifactId>
                <version>${liquibase.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>nl.martijndwars</groupId>
                <artifactId>web-push</artifactId>
                <version>${web-push.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bouncycastle.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>com.lmax</groupId>
                <artifactId>disruptor</artifactId>
                <version>${disruptor.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>com.github.ben-manes.caffeine</groupId>
                <artifactId>caffeine</artifactId>
                <version>${caffeine.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis-spring.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-autoconfigure</artifactId>
                <version>${mybatis-spring.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis-spring</artifactId>
                <version>${mybatis-spring.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${mybatis.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
